### ISSUE TITLE
Hardhat-Fund-Me: Error Processing 01-deploy-fund-me on Rinkeby Testnet 

### ISSUE THREAD

**Issue by dibakarsutradhar** [dibakarsutradhar/smart-contracts#13]
I've been trying to deploy the contract to rinkeby testnet, but getting an error on the `01-deploy-fund-me.js` file. It's working perfectly on the local chain.

The Error - 
```
----------------------------------------------------
Deploying FundMe and waiting for confirmations...
An unexpected error occurred:


Error: ERROR processing /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/deploy/01-deploy-fund-me.js:
Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.6.1) (argument="priceFeedAddress", value=undefined, code=INVALID_ARGUMENT, version=abi/5.6.3)
    at Logger.makeError (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.throwArgumentError (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/logger/src.ts/index.ts:277:21)
    at AddressCoder.Coder._throwError (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/abi/src.ts/coders/abstract-coder.ts:68:16)
    at AddressCoder.encode (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/abi/src.ts/coders/address.ts:22:18)
    at /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/abi/src.ts/coders/array.ts:71:19
    at Array.forEach (<anonymous>)
    at pack (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/abi/src.ts/coders/array.ts:54:12)
    at TupleCoder.encode (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/abi/src.ts/coders/tuple.ts:54:20)
    at AbiCoder.encode (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:111:15)
    at DeploymentsManager.executeDeployScripts (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at DeploymentsManager.runDeploy (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
    at SimpleTaskDefinition.action (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:438:5)
    at Environment._runTaskDefinition (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:584:32)
    at Environment._runTaskDefinition (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at SimpleTaskDefinition.action (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-fund-me/node_modules/hardhat-deploy/src/index.ts:669:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I understand this has something to do with my fundMe function. So here's the deploy sciprt - 
```
const { getNamedAccounts, deployments, network } = require('hardhat');
const {
  networkConfig,
  developmentChains,
} = require('../helper-hardhat-config');
const { verify } = require('../utils/verify');

module.exports = async ({ getNamedAccounts, deployments }) => {
  const { deploy, log } = deployments;
  const { deployer } = await getNamedAccounts();
  const chainId = network.config.chainId;

  // If chainId is X use address Y
  let ethUsdPriceFeedAddress;

  if (chainId == 31337) {
    const ethUsdAggregator = await deployments.get('MockV3Aggregator');
    ethUsdPriceFeedAddress = ethUsdAggregator.address;
  } else {
    ethUsdPriceFeed = networkConfig[chainId]['ethUsdPriceFeed'];
  }

  // If the contract doesn't exist, deploy a minimal version of
  // for the local testing

  log('----------------------------------------------------');
  log('Deploying FundMe and waiting for confirmations...');

  const fundMe = await deploy('FundMe', {
    from: deployer,
    args: [ethUsdPriceFeedAddress],
    log: true,
    // we need to wait if on a live network so we can verify properly
    waitConfirmations: network.config.blockConfirmations || 1,
  });

  log(`FundMe deployed at ${fundMe.address}`);

  if (
    !developmentChains.includes(network.name) &&
    process.env.ETHERSCAN_API_KEY
  ) {
    // verify
    await verify(fundMe.address, [ethUsdPriceFeedAddress]);
  }

  log('----------------------------------------');
};

module.exports.tags = ['all', 'fundme '];
```

I have checked my `hardhat.config` as well - 
```
solidity: {
    compilers: [{ version: '0.8.8' }, { version: '0.6.6' }],
  },
  defaultNetwork: 'hardhat',
  networks: {
    rinkeby: {
      url: RINKEBY_RPC_URL,
      accounts: [RINKEBY_PRIVATE_KEY],
      chainId: 4,
      blockConfirmations: 6,
    },
```

And here's the `helper-hardhat-config` file - 
```
const networkConfig = {
  4: {
    name: 'rinkeby',
    ethUsdPriceFeed: 'chain.link price feed address',
  },
  31337: {
    name: 'localhost',
  },
};

const developmentChains = ['hardhat', 'localhost'];
const DECIMALS = '8';
const INITIAL_ANSWER = '20000000000';

module.exports = { networkConfig, developmentChains, DECIMALS, INITIAL_ANSWER };
```
`verify.js` - 
```
const { run } = require('hardhat');

const verify = async (contractAddress, args) => {
  console.log('Verifying Contract...');
  try {
    await run('verify:verify', {
      address: contractAddress,
      constructorArguments: args,
    });
  } catch (e) {
    if (e.message.toLowerCase().includes('already verified')) {
      console.log('Contract Already Verified!');
    } else {
      console.log(e);
    }
  }
};

module.exports = { verify };

```

Was wondering if anyone has faced the same issue.

**Comment by dibakarsutradhar** [comment]
I have added the same issue in https://github.com/smartcontractkit/full-blockchain-solidity-course-js/discussions/49#discussion-4109757
