### ISSUE TITLE
Random IPFS NFT - Deploy & Unit Test Fail || Error: missing argument: passed to contract (count=1, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.6.2)

### ISSUE THREAD

**Issue by dibakarsutradhar** [dibakarsutradhar/smart-contracts#36]
Error Code - 
```javascript
1) Random IPFS NFT Unit Tests
       "before each" hook for "sets starting values correctly":
     ERROR processing /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/deploy/02-deploy-random-ipfs.js:
Error: missing argument: passed to contract (count=1, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.6.2)
    at Logger.makeError (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.checkArgumentCount (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/logger/src.ts/index.ts:332:18)
    at /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/src.ts/index.ts:187:12
    at step (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at populateTransaction (/Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/lib/index.js:152:12)
  Error: ERROR processing /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/deploy/02-deploy-random-ipfs.js:
  Error: missing argument: passed to contract (count=1, expectedCount=2, code=MISSING_ARGUMENT, version=contracts/5.6.2)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at Logger.checkArgumentCount (node_modules/@ethersproject/logger/src.ts/index.ts:332:18)
      at /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/src.ts/index.ts:187:12
      at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at /Users/dibakar/Downloads/Projects/smart-contracts/hardhat-nft/backend/node_modules/@ethersproject/contracts/lib/index.js:23:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/@ethersproject/contracts/lib/index.js:19:12)
      at populateTransaction (node_modules/@ethersproject/contracts/lib/index.js:152:12)
      at DeploymentsManager.executeDeployScripts (node_modules/hardhat-deploy/src/DeploymentsManager.ts:1222:19)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
      at DeploymentsManager.runDeploy (node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:5)
      at Object.fixture (node_modules/hardhat-deploy/src/DeploymentsManager.ts:315:9)
      at Context.<anonymous> (test/unit/randomIpfsNft.test.js:13:9)
```

Unit Test - `beforeEach()` - 

```javascript
beforeEach(async () => {
        accounts = await ethers.getSigners();
        deployer = accounts[0];
        await deployments.fixture(['mocks', 'randomipfs']);
        randomIpfsNft = await ethers.getContract('RandomIPFSNft');
        vrfCoordinatorV2Mock = await ethers.getContract('VRFCoordinatorV2Mock');
      });
```

Smart Contract Constructor - 
```solidity
constructor(
        address vrfCoordinatorV2,
        uint64 subscriptionId,
        bytes32 gasLane,
        uint256 mintFee,
        uint32 callBackGasLimit,
        string[3] memory dogTokenUris
    ) VRFConsumerBaseV2(vrfCoordinatorV2) ERC721("Random IPFS NFT", "RIN") {
        i_vrfCoordinator = VRFCoordinatorV2Interface(vrfCoordinatorV2);
        i_subscriptionId = subscriptionId;
        i_gasLane = gasLane;
        i_callBackGasLimit = callBackGasLimit;
        i_mintFee = mintFee;
        _initializeContract(dogTokenUris);
    }
```

**Comment by dibakarsutradhar** [comment]
#37

**Comment by dibakarsutradhar** [comment]
Figured out the error. I wasn't funding the subscription.

```javascript
await vrfCoordinatorV2Mock.fundSubscription(subscriptionId, FUND_AMOUNT);
```

The full code block - 
```typescript
if (chainId == 31337) {
    // Create VRF Subscription
    const vrfCoordinatorV2Mock = await ethers.getContract(
      'VRFCoordinatorV2Mock'
    );
    vrfCoordinatorV2Address = vrfCoordinatorV2Mock.address;
    const tx = await vrfCoordinatorV2Mock.createSubscription();
    const txReceipt = await tx.wait();
    subscriptionId = txReceipt.events[0].args.subId;
    await vrfCoordinatorV2Mock.fundSubscription(subscriptionId, FUND_AMOUNT);
  } else {
    vrfCoordinatorV2Address = networkConfig[chainId!].vrfCoordinatorV2;
    subscriptionId = networkConfig[chainId!].subscriptionId;
  }
```

Pushing the fix in the typescript version.
